ARG R_VERSION=3.6.3
FROM rocker/r-ver:${R_VERSION}

ENV RENV_PATHS_CACHE=/renv/cache
ENV RENV_PATHS_ROOT=/renv

WORKDIR /renv

RUN apt-get update && \
    apt-get install -y \
        libcurl4-openssl-dev \
        libssl-dev \
        libxml2-dev \
        procps \
        python3-pip

RUN pip3 install radian

RUN Rscript -e '\
    install.packages("renv");\
    install.packages("languageserver", Ncpus = 16)\
    '

COPY scripts/entrypoint.sh /usr/local/bin/renv-entrypoint.sh
ENTRYPOINT ["renv-entrypoint.sh"]

CMD ["radian"]
