ARG R_VERSION=3.6.3

FROM rocker/r-ver:${R_VERSION}

WORKDIR /renv

RUN Rscript -e 'install.packages("renv")'

RUN apt-get update
RUN apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev procps
RUN Rscript -e 'install.packages("languageserver", Ncpus = 16)'

RUN apt-get install -y python3-pip
RUN pip3 install radian

COPY scripts/entrypoint.sh /usr/local/bin/renv-entrypoint.sh
ENTRYPOINT ["renv-entrypoint.sh"]

CMD ["radian"]
