on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      REPOSITORY: vigenere23/renv-${{ matrix.stage }}

    strategy:
      matrix:
        stage:
          - minimal
          - dev
        r_version:
          - 3.6.3

    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.r_version }}-${{ matrix.stage }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.r_version }}-${{ matrix.stage }}
            ${{ runner.os }}-buildx-${{ matrix.r_version }}
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          target: final
          build-args: |
            R_VERSION=${{ matrix.r_version }}
            STAGE=${{ matrix.stage }}
          tags: ${{ env.REPOSITORY }}:${{ matrix.r_version }}
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.REPOSITORY }}
          short-description: A pre-built Docker image setup with `renv` dependencies.

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
